## 04. Pandas
- 파이썬 기반의 강력하고 사용하기 쉬운 데이터 분석 및 조작 라이브러리

In [2]:
import pandas as pd

print(pd.__version__)

2.3.3

### Pandas의 핵심 자료 구조
- Series
- DataFrame

### Series
- 인덱스(라벨)가 붙은 1차원 배열
- 인덱스 이름을 직접 지정할 수 있음

In [3]:
# 시리즈 생성
# 1. 리스트로 생성
data = [10, 20, 30, 40]
s = pd.Series(data)
print(s)

# 0    10
# 1    20
# 2    30
# 3    40
# dtype: int64

0    10
1    20
2    30
3    40
dtype: int64

In [4]:
# 2. 인덱스를 직접 지정
s = pd.Series(data, index=["a", "b", "c", "d"])
print(s)

# a    10
# b    20
# c    30
# d    40
# dtype: int64

a    10
b    20
c    30
d    40
dtype: int64

In [5]:
# 3. 딕셔너리로 생성 
data = {'서울' : 100, '부산' : 200, '대구' : 300, '제주' : 400}
s = pd.Series(data)
print(s)

# 서울    100
# 부산    200
# 대구    300
# 제주    400
# dtype: int64

서울    100
부산    200
대구    300
제주    400
dtype: int64

In [6]:
# 4. 하나의 값으로 시리즈를 생성
s = pd.Series(7, index=["가", "나", "다"])
print(s)

# 가    7
# 나    7
# 다    7
# dtype: int64

가    7
나    7
다    7
dtype: int64

In [7]:
# 시리즈의 주요 속성
data = [10, 20, 30, 40]
s = pd.Series(data, index=['a', 'b', 'c', 'd'], name='test data')
print("values", s.values) # 실제 데이터 배열    values [10 20 30 40]
print("index", s.index)   # 인덱스 객체         index Index(['a', 'b', 'c', 'd'], dtype='object')
print("dtype", s.dtype)   # 실제 데이터의 타입  dtype int64
print("size", s.size)     # 데이터의 개수       size 4
print("shape", s.shape)   # 배열의 형태         shape (4,)
print("name", s.name)     # 시리즈의 이름       name test data

values [10 20 30 40]
index Index(['a', 'b', 'c', 'd'], dtype='object')
dtype int64
size 4
shape (4,)
name test data

In [8]:
# 시리즈의 연산
s1 = pd.Series([10, 20, 30], index=["a", "b", "c"])
s2 = pd.Series([5, 6, 7], index=["c", "b", "d"])

result = s1 + s2
print(result)

# a     NaN
# b    26.0
# c    35.0
# d     NaN
# dtype: float64

a     NaN
b    26.0
c    35.0
d     NaN
dtype: float64

In [9]:
# 브로드 캐스팅
s = pd.Series([5, 10, 15], index=['x', 'y', 'z'])

print(s + 3)
# x     8
# y    13
# z    18
# dtype: int64
print(s * 2)
# x    10
# y    20
# z    30
# dtype: int64

x     8
y    13
z    18
dtype: int64
x    10
y    20
z    30
dtype: int64

In [10]:
# 불리언 연산 및 인덱싱
s = pd.Series([50, 60, 70, 80, 90, 100])

mask = s > 70
print(mask)
# 0    False
# 1    False
# 2    False
# 3     True
# 4     True
# 5     True
# dtype: bool
print(s[mask])
# 3     80
# 4     90
# 5    100
# dtype: int64

0    False
1    False
2    False
3     True
4     True
5     True
dtype: bool
3     80
4     90
5    100
dtype: int64

In [ ]:
# 실습1. Series 연습(1)
# 1. 파이썬 리스트 [5, 10, 15, 20]을 이용해 Series를 생성하세요.
data = pd.Series([5, 10, 15, 20])
print("문제 1. \n", data)

# 2. 값 [90, 80, 85, 70]에 대해 인덱스를 각각 '국어', '영어', '수학', '과학'으로 지정한 Series를 만드세요.
subjects = pd.Series([90, 80, 85, 70], index=["국어", "영어", "수학", "과학"])
print("\n문제 2. \n", subjects)

# 3. {'서울': 950 , '부산': 340 , '인천': 520} 딕셔너리를 이용해 Series를 만들고, 인천의 값을 출력하세요.
city_dict = {'서울': 950 , '부산': 340 , '인천': 520}
city = pd.Series(city_dict)
print("\n문제 3. \n", city)

문제 1.
 0     5
1    10
2    15
3    20
dtype: int64

문제 2.
 국어    90
영어    80
수학    85
과학    70
dtype: int64

문제 3.
 서울    950
부산    340
인천    520
dtype: int64

In [12]:
# 실습1. Series 연습(2)
# 4. Series [1, 2, 3, 4]를 만들고, 데이터 타입(dtype)을 출력하세요.
data = pd.Series([1, 2, 3, 4])
print("문제 4. 데이터 타입 : ", data.dtype)

# 5. 아래 두 Series의 합을 구하세요.
s1 = pd.Series([3, 5, 7], index=['a', 'b', 'c'])
s2 = pd.Series([10, 20, 30], index=['b', 'c', 'd'])

print("\n문제 5. \n", s1 + s2)

# # 6. Series [1, 2, 3, 4, 5]의 각 값에 10을 더한 Series를 만드세요.
broad_c = pd.Series([1, 2, 3, 4, 5])

print("\n문제 6.\n", broad_c + 10)

문제 4. 데이터 타입 :  int64

문제 5.
 a     NaN
b    15.0
c    27.0
d     NaN
dtype: float64

문제 6.
 0    11
1    12
2    13
3    14
4    15
dtype: int64

### DataFrame
- 2차원 라벨 데이터 구조
- Series를 모아놓은 것
- 행과 열이 있고, 행과 열에 대해 라벨을 부여할 수 있다.

In [14]:
# DataFrame 생성

# 1. 딕셔너리로 생성
data = {
    "이름" : ['kim', 'lee', 'sin'],
    "나이" : [15, 25, 33],
    "도시" : ['서울', '부산', '대구']
}

df = pd.DataFrame(data)
df


#   이름	나이	 도시
# 0	kim	    15	    서울
# 1	lee	    25	    부산
# 2	sin	    33	    대구

    이름  나이  도시
0  kim  15  서울
1  lee  25  부산
2  sin  33  대구

In [ ]:
# 2. 리스트의 리스트(2차원 리스트)로 생성
data = [[1, "a"], [2, "b"], [3, "c"]]
df = pd.DataFrame(data, columns=["번호", "코드"])
df

#      번호    코드
#   0	1	    a
#   1	2	    b
#   2	3	    c

   번호 코드
0   1  a
1   2  b
2   3  c

In [20]:
# 3. 딕셔너리 리스트로 생성
data = [
    {'이름' : 'Kim', '나이' : 28, '도시' : '제주'},
    {'이름' : 'Choi', '나이' : 27, '도시' : '울산'}
]
df = pd.DataFrame(data, index=["bf", "gf"])
df

      이름  나이  도시
bf   Kim  28  제주
gf  Choi  27  울산

In [22]:
# 4. Series의 딕셔너리로 생성
s1 = pd.Series(["국어", "수학", "영어"], index=["a", "b", "c"])
s2 = pd.Series([100, 90, 85], index=["a", "b", "c"])

df = pd.DataFrame({"과목" : s1, "점수" : s2})
df


#       과목	점수
#   a	국어	100
#   b	수학	90
#   c	영어	85

   과목   점수
a  국어  100
b  수학   90
c  영어   85

In [29]:
# DataFrame 기본 속성
data = [
    {'이름' : 'Kim', '나이' : 28, '도시' : '제주'},
    {'이름' : 'Choi', '나이' : 27, '도시' : '울산'}
]

df = pd.DataFrame(data)

print("shape : ", df.shape)
print("columns : ", df.columns)
print("index : ", df.index)
print("dtype : ", df.dtypes)
print("values : ", df.values)
print("info : ", df.info())


# DataFrame 기본 속성
data = [
    {'이름' : 'Kim', '나이' : 28, '도시' : '제주'},
    {'이름' : 'Choi', '나이' : 27, '도시' : '울산'}
]

df = pd.DataFrame(data)

print("shape : ", df.shape)
print("columns : ", df.columns)
print("index : ", df.index)
print("dtype : ", df.dtypes)
print("values : ", df.values)
print("info : ", df.info())


# shape :  (2, 3)
# columns :  Index(['이름', '나이', '도시'], dtype='object')
# index :  RangeIndex(start=0, stop=2, step=1)
# dtype :  이름    object
# 나이     int64
# 도시    object
# dtype: object
# values :  [['Kim' 28 '제주']
#  ['Choi' 27 '울산']]
# <class 'pandas.core.frame.DataFrame'>
# RangeIndex: 2 entries, 0 to 1
# Data columns (total 3 columns):
#  #   Column  Non-Null Count  Dtype 
# ---  ------  --------------  ----- 
#  0   이름      2 non-null      object
#  1   나이      2 non-null      int64 
#  2   도시      2 non-null      object
# dtypes: int64(1), object(2)
# memory usage: 180.0+ bytes
# info :  None

shape :  (2, 3)
columns :  Index(['이름', '나이', '도시'], dtype='object')
index :  RangeIndex(start=0, stop=2, step=1)
dtype :  이름    object
나이     int64
도시    object
dtype: object
values :  [['Kim' 28 '제주']
 ['Choi' 27 '울산']]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      2 non-null      object
 1   나이      2 non-null      int64
 2   도시      2 non-null      object
dtypes: int64(1), object(2)
memory usage: 180.0+ bytes
info :  None
shape :  (2, 3)
columns :  Index(['이름', '나이', '도시'], dtype='object')
index :  RangeIndex(start=0, stop=2, step=1)
dtype :  이름    object
나이     int64
도시    object
dtype: object
values :  [['Kim' 28 '제주']
 ['Choi' 27 '울산']]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      2 non-null      object
 1   나이      2 non-null      int64
 2   도시      2 non-null      object
dtypes: int64(1), object(2)
memory usage: 180.0+ bytes
info :  None

In [42]:
# 실습2. DataFrame 연습(1)
# 1. 다음 데이터로 DataFrame을 생성하고, 컬럼명을'이름', '나이', '도시'로 지정하세요.
data = [['홍길동',28, '서울'], ['김철수',33, '부산'], ['이영희',25, '대구']]
df = pd.DataFrame(data, columns=["이름", "나이", "도시"])
print("문제 1. \n", df)
# 2. 아래와 같은 딕셔너리로 DataFrame을 생성하세요.
data =  {'A': [1, 2, 3], 'B': [4, 5, 6]}
df = pd.DataFrame(data)
print("\n문제 2. \n", df)

# 3. 아래 데이터를 사용해 DataFrame을 만드세요.
data = [{'과목': '수학', '점수': 90}, {'과목': '영어', '점수': 85}, {'과목': '과학', '점수': 95}]
df = pd.DataFrame(data)
print("\n문제 3. \n", df)
# 4. 아래 데이터를 사용해 DataFrame을 생성하되, 인덱스를['학생1', '학생2', '학생3']으로지정하세요.
data = {'이름': ['민수', '영희', '철수'], '점수': [80, 92, 77]}
df = pd.DataFrame(data, index=["학생1", "학생2", "학생3"])
print("\n문제 4.\n", df)

문제 1.
     이름  나이  도시
0  홍길동  28  서울
1  김철수  33  부산
2  이영희  25  대구

문제 2.
    A  B
0  1  4
1  2  5
2  3  6

문제 3.
    과목  점수
0  수학  90
1  영어  85
2  과학  95

문제 4.
      이름  점수
학생1  민수  80
학생2  영희  92
학생3  철수  77

In [ ]:
# 실습2. DataFrame 연습(2)
# 5. 아래  Series 객체 2개를 이용해 DataFrame을 만드세요.
kor = pd.Series([90, 85, 80], index=['a', 'b', 'c'])
eng = pd.Series([95, 88, 82], index=['a', 'b', 'c'])
df = pd.DataFrame({"kor" : kor, "eng" : eng})
print("문제 5. \n", df)

# 6. 아래 딕셔너리로 DataFrame을 만들고, 컬럼순서를['B', 'A']로 지정해 출력하세요.
data = {'A': [1, 2], 'B': [3, 4]}
df = pd.DataFrame(data, columns=["B", "A"])
print("\n문제 6.\n", df)

# 7. 데이터를 DataFrame으로 만들고, 컬럼명을 ['product', 'price', 'stock']으로 변경하세요.
prd = [['펜', 1000, 50], ['노트', 2000, 30]]
df_prd = pd.DataFrame(prd, columns=['product', 'price', 'stock'])
print("\n문제 7.\n", df_prd)

# 8. 아래 DataFrame을 생성한뒤, '국가' 컬럼만 추출하세요.
coun = {'국가': ['한국', '일본', '미국'], '수도': ['서울', '도쿄', '워싱턴']}
df_coun = pd.DataFrame(coun)
print("\n문제 8.\n", df_coun['국가'])

문제 5.
    kor  eng
a   90   95
b   85   88
c   80   82

문제 6.
    B  A
0  3  1
1  4  2

문제 7.
   product  price  stock
0       펜   1000     50
1      노트   2000     30

문제 8.
 0    한국
1    일본
2    미국
Name: 국가, dtype: object