# 05. Pandas

In [1]:
import pandas as pd

### 조건 필터링

In [ ]:
data = {
    '이름' : ['홍길동', '김철수', '이영희', '박민수'],
    '점수' : [90, 70, 95, 95],
    '반' : [2, 1, 1, 2]
}

df = pd.DataFrame(data)
df

#     이름	점수	반
# 0	홍길동	90	    2
# 1	김철수	70	    1
# 2	이영희	95	    1
# 3	박민수	95	    2

    이름  점수  반
0  홍길동  90  2
1  김철수  70  1
2  이영희  95  1
3  박민수  95  2

In [ ]:
mask = df['점수'] >= 80
filtered = df[mask]
filtered

# 	이름	점수	반
# 0	홍길동	90	    2
# 2	이영희	95	    1
# 3	박민수	95	    2

    이름  점수  반
0  홍길동  90  2
2  이영희  95  1
3  박민수  95  2

In [14]:
# 여러 조건 결합 : 각 조건은 반드시 괄호로 묶어야 함
# and : &
# or : |
# not : ~

# & 예시
df[(df['반'] == 1) & (df['점수'] >= 80)]
#     이름	점수	반
# 2	이영희	95	    1

# | 예시
df[(df['반'] == 2) | (df['점수'] >= 90)]
#     이름	점수	반
# 0	홍길동	90	    2
# 2	이영희	95	    1
# 3	박민수	95	    2

# ~ 예시
df
df[ ~ (df['점수'] >= 80)]
#     이름	점수	반
# 1	김철수	70	    1

    이름  점수  반
1  김철수  70  1

In [ ]:
# isin()
# 여러 값 중에 하나에 해당하는지 여부를 판단할 때 사용

# ex. 이름이 홍길동 이거나, 박민수 이거나 한 경우
mask = (df['이름'] == "홍길동") | (df['이름'] == "박민수")
df[mask]
#     이름	점수	반
# 0	홍길동	90	    2
# 3	박민수	95	    2

mask = df["이름"].isin(["홍길동", "박민수"])
df[mask]
#     이름	점수	반
# 0	홍길동	90	    2
# 3	박민수	95	    2

mask2 = ~df["이름"].isin(["홍길동", "박민수"])
df[mask2]
#     이름	점수	반
# 1	김철수	70	    1
# 2	이영희	95	    1

    이름  점수  반
1  김철수  70  1
2  이영희  95  1